name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run linter
        run: pnpm run lint:check

      - name: Run type check
        run: pnpm run typecheck

      - name: Run tests
        run: pnpm run test:prod
        env:
          VITE_APP_DADATA_API_KEY: ${{ secrets.VITE_APP_DADATA_API_KEY }}

      - name: Build library
        run: pnpm run build

  # Обязательная проверка для PR
  ci-success:
    name: CI Success
    runs-on: ubuntu-latest
    needs: [ci]
    if: always()
    steps:
      - name: Check CI status
        if: needs.ci.result != 'success'
        run: |
          echo "CI failed or was cancelled"
          exit 1
      - name: CI passed
        run: echo "All CI checks passed successfully"
